service: pipesheet

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: us-west-1

functions:
  synchronize:
    handler: handler.synchronize
    events:
      - http:
          path: /
          method: get
